version: '3.8'

services:
  backend:
    restart: always  
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"  # Exposing backend port 3000
    env_file:
      - ./backend/.env
    extra_hosts:
      - "localhost:0.0.0.0" # Ensure localhost maps correctly

  frontend:
    restart: always
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5001:5001"  # Exposing frontend port 5001
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
